### ISSUE TITLE
Private channels not being allowed to join

### ISSUE THREAD

**Issue by Syloq** [insomniacslk/irc-slack#35] opened 2018-09-26 15:22 UTC
After setting this up I noticed that when I tried to join a "private" channel on slack that it reported in the server log (and not to the client):

Cannot join channel #secret-channel-here: name_taken

I assume this is because secret/private channels on slack are treated in a completely different way. Is there a workaround for this?

**Comment by insomniacslk** [comment] 2018-09-27 16:51
hey @Syloq , thanks for reporting this bug. This sounds like a regression, I will look into it

**Comment by insomniacslk** [comment] 2018-09-27 17:05
@Syloq can you please test https://github.com/insomniacslk/irc-slack/pull/36 and let me know if this fixes the issue for you?

```
git clone https://github.com/insomniacslk/irc-slack.git -b fix_getconversations
cd irc-slack
go build
./irc-slack
```

**Comment by insomniacslk** [comment] 2018-09-27 19:10
I merged the PR, it seems to be working well. Let me know if this doesn't work for you or if you find any issue (or feel free to close this issue)

**Closed** 2018-09-27 19:10 UTC
Labels: bug

**Comment by Syloq** [comment] 2018-09-27 22:27
@insomniacslk I was able to pull this just now and it works perfectly! Thanks for the fix.

**Comment by insomniacslk** [comment] 2018-09-27 22:38
no problem, thank you and please keep testing and reporting bugs! :)
